// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyaIP4ngNk2SIOrP4CEh6Mbg8cavk79OE',
    appId: '1:263863136044:web:0aced88c29afff371f4689',
    messagingSenderId: '263863136044',
    projectId: 'flashchat-redo1',
    authDomain: 'flashchat-redo1.firebaseapp.com',
    storageBucket: 'flashchat-redo1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyDP-GBYeRvSkljPsA2JHaNtNA2h5Kfec',
    appId: '1:263863136044:android:617bc2a9e091f2c11f4689',
    messagingSenderId: '263863136044',
    projectId: 'flashchat-redo1',
    storageBucket: 'flashchat-redo1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm_1-tUGank690jsbSB68rsx_46HmMD6g',
    appId: '1:263863136044:ios:7ef9ebcbf7c906281f4689',
    messagingSenderId: '263863136044',
    projectId: 'flashchat-redo1',
    storageBucket: 'flashchat-redo1.appspot.com',
    iosBundleId: 'com.example.flashchatRedo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm_1-tUGank690jsbSB68rsx_46HmMD6g',
    appId: '1:263863136044:ios:7ef9ebcbf7c906281f4689',
    messagingSenderId: '263863136044',
    projectId: 'flashchat-redo1',
    storageBucket: 'flashchat-redo1.appspot.com',
    iosBundleId: 'com.example.flashchatRedo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrmlbcWdM_LL_bEqRA9c-z-r53dbA7Uxs',
    appId: '1:263863136044:web:520c5c2a6a58196d1f4689',
    messagingSenderId: '263863136044',
    projectId: 'flashchat-redo1',
    authDomain: 'flashchat-redo1.firebaseapp.com',
    storageBucket: 'flashchat-redo1.appspot.com',
  );
}
